###POST
POST http://localhost:8888/api/company
Content-Type: application/json

{
    "jwt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGJhYzEwMTdkNjY4ZWNjY2NkMTc5ZGQiLCJyb2xlIjpbXSwibmFtZSI6IlpoZW5jaGVuZyBDaHUiLCJjb21wYW55IjoiVE8gQkUgQlVJTEQiLCJpYXQiOjE2OTE4MDA1Nzd9.fTDo2GQd7Ri1IgPJZ156qtRQkPCMXST51UIUH1ZLHn8",
    "companyName": "Qiang Sheng Technology.Inc"
}