##get
GET http://localhost:8888/api/users

###POST
POST http://localhost:8888/api/users
Content-Type: application/json

{
    "name": "danChu",
    "email": "1234@123.com",
    "password": "122@Case1",
    "company": "not Sure"
}

### Post test user
POST http://localhost:8888/api/users
Content-Type: application/json

{
    "name": "danChu",
    "email": "test1@test.com",
    "password": "myTest1@"
}
